{% set name = "jupyterclearcheck" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterclearcheck-{{ version }}.tar.gz
  sha256: dada5bc8a531bdae9ccd6c6939c63bc13c3f8c0f209a7a3633fca32d3f9e07f4

build:
  entry_points:
    - jupyterclearcheck = jupyterclearcheck.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - pdm-backend
    - pip
  run:
    - python >=3.9
    - nbformat >=5.10.4

test:
  imports:
    - jupyterclearcheck
  commands:
    - pip check
    - jupyterclearcheck --help
  requires:
    - pip

about:
  home: https://github.com/guru-desh/JupyterClearCheck
  summary: A Python CLI to check that a Jupyter Notebook's Outputs' have been cleared.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guru-desh
